version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
    ports:
      - "${SQLSERVER_PORT}:1433"
    networks:
      - backend
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    networks:
      - backend
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${BACKEND_DEBUG}
      - SECRET_KEY=${BACKEND_SECRET_KEY}
    depends_on:
      - sqlserver

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "${FRONTEND_PORT}:8000"
    volumes:
      - ./frontend:/app
    networks:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data: